version: '3.8'
services:
  app:
    image: ahmed61911/dev-ops-project:latest
    ports:
      - "8030:80"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_NAME: registration
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: registration
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306